import type {
  WorkfeedChat,
  WorkfeedNotification,
  WorkfeedPost,
  WorkfeedStory,
} from "@/lib/workflow/workfeed/types"

export const WORKFEED_POSTS: WorkfeedPost[] = [
  {
    id: "post-1",
    kind: "boss-announcement",
    background: "linear-gradient(160deg, #f0e6ff, #ddd6fe, #c4b5fd)",
    lines: [
      {
        parts: [
          { type: "highlight", value: "mn", bg: "#7c3aed", color: "#fff" },
          { type: "text", value: " gửi c" },
        ],
      },
      {
        parts: [{ type: "highlight", value: "báo cáo", bg: "#1a1208", color: "#fff" }],
      },
      {
        parts: [
          { type: "text", value: "chạy " },
          { type: "highlight", value: "ads", bg: "#dc2626", color: "#fff" },
          { type: "text", value: " tuần rồi" },
        ],
      },
      {
        parts: [
          { type: "highlight", value: "nhé", bg: "#059669", color: "#fff" },
          { type: "text", value: " 📊" },
        ],
      },
    ],
    mentions: ["@employee2", "@dung", "@my"],
    author: {
      initials: "BS",
      avatarBg: "#1a1208",
      name: "boss",
      sub: "Manager · 8:05 AM",
    },
    tagRow: "📢 Announcement · Team",
    rail: { hearts: 5, comments: 3, repeat: 1, showRepeat: true },
    comments: [
      {
        id: "c1-1",
        author: "employee2",
        avatar: "E2",
        avatarBg: "#2563eb",
        text: "đây c ạ, em đã post lên rồi ạ 👇",
        time: "8:12 AM",
      },
      {
        id: "c1-2",
        author: "my",
        avatar: "MY",
        avatarBg: "#7c3aed",
        text: "da c ạ 🙏",
        time: "8:14 AM",
      },
      {
        id: "c1-3",
        author: "dung",
        avatar: "DU",
        avatarBg: "#059669",
        text: "dạ c ạ ✅",
        time: "8:15 AM",
      },
    ],
  },
  {
    id: "post-2",
    kind: "ads-carousel",
    author: {
      initials: "E2",
      avatarBg: "#2563eb",
      name: "employee2",
      sub: "Replying to boss · 8:12 AM",
    },
    tagRow: "📊 Báo cáo Ads Tuần 1",
    rail: { hearts: 12, comments: 4, showBookmark: true },
    slides: [
      {
        label: "1 / 3 · báo cáo ads",
        background: "linear-gradient(160deg, #d1fae5, #6ee7b7, #34d399)",
        headline: [
          { type: "highlight", value: "Tuần 1", bg: "#1a1208", color: "#fff" },
          { type: "text", value: " tăng" },
          { type: "highlight", value: "+15%", bg: "#059669", color: "#fff", large: true },
          { type: "text", value: " 📈" },
        ],
        card: { title: "performance overview", kind: "overview" },
        highlightStrip: "highlight: KOC @hienvuive — 125 likes, 30 DMs 🔥",
        swipeHint: "→ swipe để xem chi tiết",
      },
      {
        label: "2 / 3 · chi tiết kênh",
        background: "linear-gradient(160deg, #fef3c7, #fde68a, #fbbf24)",
        headline: [
          { type: "highlight", value: "TikTok", bg: "#1a1208", color: "#fff" },
          { type: "text", value: " dẫn đầu" },
          { type: "text", value: "với ROAS " },
          { type: "highlight", value: "3.2x", bg: "#f59e0b", color: "#1a1208" },
          { type: "text", value: " 🏆" },
        ],
        card: { title: "chi tiết kênh ads", kind: "channels" },
        highlightStrip: undefined,
      },
      {
        label: "3 / 3 · koc performance",
        background: "linear-gradient(160deg, #dbeafe, #93c5fd, #60a5fa)",
        headline: [
          { type: "highlight", value: "2 KOC", bg: "#2563eb", color: "#fff" },
          { type: "text", value: " top" },
          { type: "text", value: "tuần này 🌟" },
        ],
        card: { title: "KOC results", kind: "koc" },
        highlightStrip:
          "brief thêm 2 KOC mới tuần sau · tăng ngân sách @hienvuive +500K",
      },
    ],
    comments: [
      {
        id: "c2-1",
        author: "boss",
        avatar: "BS",
        avatarBg: "#1a1208",
        text: "ok e, làm tốt lắm 👍",
        time: "8:20 AM",
      },
      {
        id: "c2-2",
        author: "dung",
        avatar: "DU",
        avatarBg: "#059669",
        text: "dạ c ạ ✅",
        time: "8:25 AM",
      },
      {
        id: "c2-3",
        author: "my",
        avatar: "MY",
        avatarBg: "#7c3aed",
        text: "okie c 🙏",
        time: "8:26 AM",
      },
      {
        id: "c2-4",
        author: "ductran",
        avatar: "DT",
        avatarBg: "#0ea5e9",
        text: "vâng c ạ, đã check rồi",
        time: "8:28 AM",
      },
    ],
  },
  {
    id: "post-3",
    kind: "meeting-notes",
    background: "linear-gradient(160deg, #dbeafe, #bfdbfe, #93c5fd)",
    chip: "📝 Meeting Notes · 26/5",
    headline: [
      { type: "text", value: "meeting " },
      { type: "highlight", value: "26/5", bg: "#1a1208", color: "#fff" },
      { type: "text", value: " notes 📋" },
    ],
    goal: "Campaign tháng 7-8 với 20 KOC cho Client A",
    tasks: [
      { id: "t1", label: "Research campaign ideas", assignee: "@dung", checked: false },
      { id: "t2", label: "Contact vendor video", assignee: "@my", checked: false },
      { id: "t3", label: "Set meeting with client", assignee: "@ductran", checked: true },
    ],
    videoLink: {
      title: "yêu cầu campaign từ KH",
      sub: "tap để xem video brief",
      targetPostId: "post-4",
    },
    author: {
      initials: "E2",
      avatarBg: "#2563eb",
      name: "employee2",
      sub: "9:30 AM",
    },
    rail: { hearts: 7, comments: 2, showBookmark: true },
    comments: [
      {
        id: "c3-1",
        author: "dung",
        avatar: "DU",
        avatarBg: "#059669",
        text: "dạ c, đang làm rồi ạ 💪",
        time: "9:35 AM",
      },
      {
        id: "c3-2",
        author: "my",
        avatar: "MY",
        avatarBg: "#7c3aed",
        text: "e nhận task rồi ạ 🙏",
        time: "9:36 AM",
      },
    ],
  },
  {
    id: "post-4",
    kind: "video-brief",
    mentions: ["@dung", "@my", "@ductran"],
    stickerTitle: "XEM KỸ NHÉ MN",
    badge: "YÊU CẦU CAMPAIGN TỪ KH",
    subtitles: [
      { line: "CẢNH TRUNG | MEDIUM SHOT", style: "shot" },
      { line: "Đặt máy tính xuống", style: "vi" },
      { line: "Putting down the MacBook", style: "en" },
    ],
    author: {
      initials: "E2",
      avatarBg: "#2563eb",
      name: "employee2",
      sub: "Video brief · 9:45 AM",
      lightText: true,
    },
    rail: { hearts: 9, comments: 3, repeat: 1, showRepeat: true, showBookmark: true, lightMode: true },
    comments: [
      {
        id: "c4-1",
        author: "dung",
        avatar: "DU",
        avatarBg: "#059669",
        text: "xem kỹ rồi c ơi, hiểu yêu cầu 👌",
        time: "9:50 AM",
      },
      {
        id: "c4-2",
        author: "my",
        avatar: "MY",
        avatarBg: "#7c3aed",
        text: "okie c e chuẩn bị props rồi ạ",
        time: "9:52 AM",
      },
      {
        id: "c4-3",
        author: "ductran",
        avatar: "DT",
        avatarBg: "#0ea5e9",
        text: "dạ c ạ 🎬",
        time: "9:53 AM",
      },
    ],
  },
]

export const WORKFEED_STORIES: WorkfeedStory[] = [
  {
    id: "story-my",
    author: "my",
    initials: "MY",
    avatarBg: "#7c3aed",
    background: "linear-gradient(160deg, #292018, #1a1208, #0f0a06)",
    badge: "on location 🎬",
    badgeClass: "bg-emerald-400 text-emerald-950",
    text: "đang quay video cho Client A tại studio Hà Nội — cảnh mở đầu xong rồi c ơi @boss @employee2 🙌",
    viewers: "BS + E2 · 2 người đã xem",
  },
  {
    id: "story-dung",
    author: "dung",
    initials: "DU",
    avatarBg: "#059669",
    background: "linear-gradient(160deg, #312e81, #1e1b4b, #0f0a1a)",
    badge: "progress update 📄",
    badgeClass: "bg-violet-500 text-white",
    text: "research campaign ideas xong rồi ạ — đang viết brief cho cả nhóm @employee2 @boss",
    viewers: "",
  },
  {
    id: "story-ductran",
    author: "ductran",
    initials: "DT",
    avatarBg: "#0ea5e9",
    background: "linear-gradient(160deg, #14532d, #052e16, #0a0f0a)",
    badge: "task done ✅",
    badgeClass: "bg-emerald-400 text-emerald-950",
    text: "confirmed vendor xong rồi ạ, gửi contract tối hôm nay — @employee2 check email giúp c nhé 🤝",
    viewers: "",
  },
]

export const WORKFEED_NOTIFICATIONS: WorkfeedNotification[] = [
  {
    id: "n-my",
    kind: "story",
    author: "my",
    initials: "MY",
    avatarBg: "#7c3aed",
    text: "Story",
    time: "",
    storyId: "story-my",
  },
  {
    id: "n-dung",
    kind: "story",
    author: "dung",
    initials: "DU",
    avatarBg: "#059669",
    text: "Story",
    time: "",
    storyId: "story-dung",
  },
  {
    id: "n-ductran",
    kind: "story",
    author: "ductran",
    initials: "DT",
    avatarBg: "#0ea5e9",
    text: "Story",
    time: "",
    storyId: "story-ductran",
  },
  {
    id: "n-act-my",
    kind: "activity",
    author: "my",
    initials: "MY",
    avatarBg: "#7c3aed",
    text: "đang quay video tại studio",
    time: "còn 22h",
    emoji: "🎥",
  },
  {
    id: "n-act-dung",
    kind: "activity",
    author: "dung",
    initials: "DU",
    avatarBg: "#059669",
    text: "research xong rồi ạ",
    time: "còn 23h",
    emoji: "📝",
  },
  {
    id: "n-act-ductran",
    kind: "activity",
    author: "ductran",
    initials: "DT",
    avatarBg: "#0ea5e9",
    text: "confirmed vendor xong",
    time: "còn 23h",
    emoji: "✅",
  },
  {
    id: "n-like-boss",
    kind: "like",
    author: "boss",
    initials: "BS",
    avatarBg: "#1a1208",
    text: "liked your báo cáo post",
    time: "8:20 AM",
    emoji: "❤️",
  },
]

export const WORKFEED_CHATS: WorkfeedChat[] = [
  {
    id: "chat-team-a",
    title: "Team Campaign A",
    avatar: "TM",
    avatarBg: "#2563eb",
    preview: "boss: oke e 👍",
    time: "8:25",
    unread: 3,
    messages: [
      {
        id: "m1",
        sender: "boss",
        kind: "table",
        align: "left",
        table: {
          headers: ["Chi phí lưu kho", "Vận chuyển", "Nhân công SX"],
        },
        text: "mấy chi phí này là chi phí gì vậy em?",
      },
      {
        id: "m2",
        sender: "employee2",
        kind: "text",
        align: "right",
        text: "Dạ em gửi ạ 👇",
      },
      {
        id: "m3",
        sender: "employee2",
        kind: "list-card",
        align: "right",
        listCard: {
          items: [
            "1. chi phí lưu kho",
            "2. phí vận chuyển",
            "3. nhân công sản xuất",
          ],
          caption: "chi tiết 3 khoản",
        },
      },
      {
        id: "m4",
        sender: "boss",
        kind: "text",
        align: "left",
        text: "oke e 👍",
      },
    ],
  },
]
