import type { WorkfeedMoodboardProject, WorkfeedMoodPin } from "@/lib/workflow/workfeed/types"

export const WORKFEED_MOODBOARD_PROJECTS: WorkfeedMoodboardProject[] = [
  { id: "proj-client-a", name: "Client A Campaign", color: "#2563eb" },
  { id: "proj-brand", name: "Brand refresh", color: "#7c3aed" },
  { id: "proj-studio", name: "Studio / B-roll", color: "#059669" },
]

export const REFERENCE_CAMPAIGNS_PROJECT_ID = "proj-winning-ads"

/** Successful ad campaigns from other brands — inspiration library */
export const WORKFEED_REFERENCE_CAMPAIGNS: WorkfeedMoodPin[] = [
  {
    id: "ref-shopee",
    brand: "Shopee",
    title: "11.11 Mega Sale · KOC blitz",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(145deg, #ee4d2d 0%, #f97316 45%, #fbbf24 100%)",
    imageUrl: "/moodboard/_-53-fe8aed8d-f64d-4dc3-8647-69967bdf5eee.png",
    height: 240,
    tags: ["ecommerce", "koc", "sale"],
    channel: "TikTok + Live",
    statLine: "ROAS 5.1x · 180M impressions",
    saved: false,
  },
  {
    id: "ref-grab",
    brand: "Grab",
    title: "GrabFood · “Order in 30s” UGC",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(160deg, #059669 0%, #10b981 50%, #064e3b 100%)",
    imageUrl: "/moodboard/_-54-9af3e84a-e85d-4bf6-abe4-c48014a7d8a2.png",
    height: 200,
    tags: ["ugc", "food", "hook"],
    channel: "TikTok",
    statLine: "CTR +42% vs benchmark",
    saved: true,
  },
  {
    id: "ref-vinamilk",
    brand: "Vinamilk",
    title: "Sữa tươi · Gia đình Việt",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(180deg, #1d4ed8 0%, #60a5fa 55%, #dbeafe 100%)",
    imageUrl: "/moodboard/_-52-eab396df-084f-40d2-8f3b-5f9672eabc8f.png",
    height: 260,
    tags: ["tvc", "emotion", "family"],
    channel: "YouTube + FB",
    statLine: "12M views · #1 trending VN",
    saved: false,
  },
  {
    id: "ref-nike",
    brand: "Nike",
    title: "You Can’t Stop Us · split screen",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(180deg, #0f0f0a 0%, #1a1a1a 60%, #404040 100%)",
    height: 220,
    tags: ["sports", "edit", "hero"],
    channel: "Multi-platform",
    statLine: "Award-winning · 50M+ views",
    saved: false,
  },
  {
    id: "ref-apple",
    brand: "Apple",
    title: "Shot on iPhone · macro product",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(160deg, #1c1917 0%, #44403c 40%, #fafaf9 100%)",
    height: 180,
    tags: ["product", "minimal", "cinematic"],
    channel: "Instagram",
    statLine: "High save rate · premium look",
    saved: true,
  },
  {
    id: "ref-spotify",
    brand: "Spotify",
    title: "Wrapped · personalized stories",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(135deg, #1db954 0%, #191414 50%, #535353 100%)",
    height: 250,
    tags: ["personalization", "data", "story"],
    channel: "In-app + Social",
    statLine: "60M shares globally",
    saved: false,
  },
  {
    id: "ref-liquid",
    brand: "Liquid Death",
    title: "Murder your thirst · absurd humor",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(180deg, #18181b 0%, #3f3f46 100%)",
    height: 190,
    tags: ["humor", "brand voice", "disrupt"],
    channel: "TikTok",
    statLine: "CPM −35% vs category",
    saved: false,
  },
  {
    id: "ref-duolingo",
    brand: "Duolingo",
    title: "Unhinged mascot · comment replies",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(160deg, #58cc02 0%, #89e219 40%, #1cb0f6 100%)",
    height: 210,
    tags: ["mascot", "social", "meme"],
    channel: "TikTok",
    statLine: "Follower growth +8x YoY",
    saved: false,
  },
  {
    id: "ref-momo",
    brand: "MoMo",
    title: "Lì xì Tết · gamified AR filter",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(145deg, #a21caf 0%, #ec4899 50%, #f472b6 100%)",
    height: 230,
    tags: ["fintech", "tết", "ar"],
    channel: "TikTok + Zalo",
    statLine: "4.2M filter uses · ROAS 3.8x",
    saved: false,
  },
  {
    id: "ref-heineken",
    brand: "Heineken",
    title: "Cheers to all · inclusive toast",
    projectId: REFERENCE_CAMPAIGNS_PROJECT_ID,
    gradient: "linear-gradient(180deg, #14532d 0%, #166534 50%, #fbbf24 100%)",
    height: 200,
    tags: ["lifestyle", "night", "toast"],
    channel: "YouTube",
    statLine: "Brand lift +18 pts",
    saved: false,
  },
]

export const WORKFEED_MOOD_PINS: WorkfeedMoodPin[] = [
  {
    id: "pin-1",
    title: "Warm desk · MacBook hero",
    projectId: "proj-client-a",
    gradient: "linear-gradient(145deg, #2a1f12 0%, #0f0f0a 50%, #1a1510 100%)",
    imageUrl: "/moodboard/_-56-eda76165-67b3-4807-b8c1-65e8e34e0d82.png",
    height: 220,
    tags: ["video", "product"],
    saved: true,
  },
  {
    id: "pin-2",
    title: "TikTok text sticker style",
    projectId: "proj-client-a",
    gradient: "linear-gradient(160deg, #f0e6ff, #c4b5fd)",
    imageUrl: "/moodboard/_-55-16d95a6b-eaad-42e0-bae5-df354abaea50.png",
    height: 160,
    tags: ["typography"],
    saved: false,
  },
  {
    id: "pin-3",
    title: "KOC talking head — ring light",
    projectId: "proj-client-a",
    gradient: "linear-gradient(180deg, #1e293b, #0f172a)",
    height: 280,
    tags: ["koc", "studio"],
    saved: true,
  },
  {
    id: "pin-4",
    title: "Summer palette · Client A",
    projectId: "proj-brand",
    gradient: "linear-gradient(135deg, #fef3c7, #fbbf24, #f59e0b)",
    height: 140,
    tags: ["color"],
    saved: false,
  },
  {
    id: "pin-5",
    title: "Carousel ad — 4:5 grid",
    projectId: "proj-brand",
    gradient: "linear-gradient(160deg, #d1fae5, #34d399)",
    height: 200,
    tags: ["layout", "ads"],
    saved: true,
  },
  {
    id: "pin-6",
    title: "Studio wide — Hà Nội",
    projectId: "proj-studio",
    gradient: "linear-gradient(160deg, #292018, #1a1208)",
    imageUrl: "/moodboard/__________-7bcc7a79-b56a-4dfb-a247-a608bcff59ab.png",
    height: 240,
    tags: ["location"],
    saved: false,
  },
  {
    id: "pin-7",
    title: "Motion blur transition",
    projectId: "proj-studio",
    gradient: "linear-gradient(90deg, #1a4e7a, #93c5fd)",
    height: 180,
    tags: ["motion"],
    saved: false,
  },
  {
    id: "pin-8",
    title: "UGC phone POV",
    projectId: "proj-client-a",
    gradient: "linear-gradient(180deg, #4c1d95, #1e1b4b)",
    height: 260,
    tags: ["ugc", "mobile"],
    saved: true,
  },
  {
    id: "pin-9",
    title: "Minimal white brief deck",
    projectId: "proj-brand",
    gradient: "linear-gradient(180deg, #f8fafc, #e2e8f0)",
    height: 150,
    tags: ["deck"],
    saved: false,
  },
  {
    id: "pin-10",
    title: "End card — logo lockup",
    projectId: "proj-client-a",
    gradient: "linear-gradient(145deg, #c8102e, #1a1208)",
    height: 190,
    tags: ["brand"],
    saved: false,
  },
]
